cuda: "all"
model:
    arch: dkresnet
    depth: 50
data:
    dataset: cifar10
    train_dir: /home/xliu/dataset/CIFAR
    val_dir: /home/xliu/dataset/CIFAR
    workers: 16
training:
#    runid: xxxxx
#    seed: 1337
    epochs: 200
    batch_size: 256
    loss:
        name: 'label_smooth'
        smoothing: 0.1
    optimizer:
        name: 'sgd'
        lr: 0.1  #for imagenet, lr = 0.1 * batch_size / 256
        weight_decay: 0.0005
        momentum: 0.9
    lr_schedule:
        name: 'multi_step'
        milestones: [100,150]
        gamma: 0.1
    save_interval: 5
    resume: save_model.pkl
    best_model: best_model.pkl